const U=process.env.SUPABASE_URL,K=process.env.SUPABASE_SECRET_KEY,H={apikey:K,Authorization:"Bearer "+K,"Content-Type":"application/json"};
export default async function h(req,res){try{
 if(req.method==="GET"){const since=new Date(Date.now()-7*864e5).toISOString();const [er,lr,fr]=await Promise.all([fetch(U+"/rest/v1/cleaning_funnel_events?created_at=gte."+encodeURIComponent(since)+"&select=session_id,event_name",{headers:H}),fetch(U+"/rest/v1/cleaning_leads?select=*&order=appointment_date.asc,created_at.desc",{headers:H}),fetch(U+"/rest/v1/cleaning_followups?status=eq.due&select=*&order=due_date.asc",{headers:H})]);const ev=await er.json(),leads=await lr.json(),followups=await fr.json(),metrics={};for(const e of ev){metrics[e.event_name]??=new Set();metrics[e.event_name].add(e.session_id)}for(const k in metrics)metrics[k]=metrics[k].size;return res.status(200).json({metrics,leads,followups})}
 if(req.method==="PATCH"){const id=Number(req.query.id),b=req.body||{};if(!id)return res.status(400).json({error:"Valid job required"});
  if(b.action==="reschedule"){const q=await fetch(U+"/rest/v1/cleaning_leads?service_type=eq.home&appointment_date=eq."+encodeURIComponent(b.date)+"&appointment_time=eq."+encodeURIComponent(b.time)+"&status=neq.cancelled&id=neq."+id+"&select=id",{headers:H});if((await q.json()).length)return res.status(409).json({error:"That time is already booked"});const r=await fetch(U+"/rest/v1/cleaning_leads?id=eq."+id,{method:"PATCH",headers:H,body:JSON.stringify({appointment_date:b.date,appointment_time:b.time})});if(!r.ok)throw Error(await r.text());return res.json({ok:true})}
  if(b.action==="complete"){const g=await fetch(U+"/rest/v1/cleaning_leads?id=eq."+id+"&select=*",{headers:H}),rows=await g.json();if(!rows.length)return res.status(404).json({error:"Job not found"});const x=rows[0],freq=["once","weekly","biweekly","monthly"].includes(b.frequency)?b.frequency:"once",rp=freq==="once"?null:Math.round(Number(x.quoted_price||0)*(1-({monthly:.10,biweekly:.15,weekly:.20}[freq]||0)));await fetch(U+"/rest/v1/cleaning_leads?id=eq."+id,{method:"PATCH",headers:H,body:JSON.stringify({status:"completed",completed_at:new Date().toISOString(),archived:true,maintenance_plan:freq,recurring_price:rp})});if(freq!=="once"){const days=freq==="weekly"?7:freq==="biweekly"?14:30,d=new Date((x.appointment_date||new Date().toISOString().slice(0,10))+"T12:00:00");d.setDate(d.getDate()+days);await fetch(U+"/rest/v1/cleaning_followups",{method:"POST",headers:H,body:JSON.stringify({lead_id:id,due_date:d.toISOString().slice(0,10),frequency:freq,name:x.name,phone:x.phone,email:x.email,address:x.address,cleaning_type:x.cleaning_type,quoted_price:x.quoted_price,recurring_price:rp})})}return res.json({ok:true})}
  if(b.action==="book_followup"){const fid=Number(b.followup_id);const fg=await fetch(U+"/rest/v1/cleaning_followups?id=eq."+fid+"&select=*",{headers:H}),fs=await fg.json();if(!fs.length)return res.status(404).json({error:"Follow-up not found"});const fup=fs[0];const orig=await fetch(U+"/rest/v1/cleaning_leads?id=eq."+fup.lead_id+"&select=*",{headers:H}),os=await orig.json();if(!os.length)return res.status(404).json({error:"Customer record not found"});const o=os[0];const q=await fetch(U+"/rest/v1/cleaning_leads?service_type=eq.home&appointment_date=eq."+encodeURIComponent(b.date)+"&appointment_time=eq."+encodeURIComponent(b.time)+"&status=neq.cancelled&select=id",{headers:H});if((await q.json()).length)return res.status(409).json({error:"That time is already booked"});const payload={...o};delete payload.id;delete payload.created_at;delete payload.completed_at;payload.appointment_date=b.date;payload.appointment_time=b.time;payload.status="booked";payload.archived=false;payload.maintenance_plan=fup.frequency;const nr=await fetch(U+"/rest/v1/cleaning_leads",{method:"POST",headers:{...H,Prefer:"return=representation"},body:JSON.stringify(payload)});if(!nr.ok)throw Error(await nr.text());await fetch(U+"/rest/v1/cleaning_followups?id=eq."+fid,{method:"PATCH",headers:H,body:JSON.stringify({status:"booked"})});return res.json({ok:true,lead:(await nr.json())[0]})}
  if(b.action==="archive"||b.action==="cancel"){const vals=b.action==="cancel"?{status:"cancelled",archived:true}:{archived:true};await fetch(U+"/rest/v1/cleaning_leads?id=eq."+id,{method:"PATCH",headers:H,body:JSON.stringify(vals)});return res.json({ok:true})}
  return res.status(400).json({error:"Unknown action"});
 }
 return res.status(405).end();
}catch(e){console.error(e);res.status(500).json({error:"dashboard failed"})}}